set -g mouse on
set -g prefix2 C-Space
bind C-Space send-prefix -2
set -g history-limit 50000

set -g base-index 1
set -g renumber-windows on

# Status bar
set -g status-position top
set -g status-interval 5
set -g status-style "#{?window_zoomed_flag,bg=#062417 fg=#90bbc5,bg=#90bbc5 fg=#062417}"
set -g status-left "#{?client_prefix,#[bg=#7aa2f7 fg=#1a1b26 bold] ⌨  #S #[default],#[bold] #S #[default]}| "

# Simplify window names, bold current window
setw -g window-status-format " #I:#{window_name} "
setw -g window-status-current-format "#[bold] #I:#{window_name} #[default]"
setw -g window-status-separator ""

# Vim integration
set -g focus-events on

# Intuitive splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

