set -g mouse on
set -g prefix2 C-Space
bind C-Space send-prefix -2
set -g history-limit 50000

set -g base-index 1
set -g renumber-windows on

#############
# STATUSBAR #
#############

set -g status-position top
set -g status-interval 5

set -g @status_bg "#cbd5e1"
set -g @status_fg "#1e293b"
set -g @status_prefix_bg "#0284c7"
set -g @status_prefix_fg "#e0f2fe"

# shared status using variables
set -g status-style "#{?window_zoomed_flag,bg=#{@status_fg} fg=#{@status_bg},bg=#{@status_bg} fg=#{@status_fg}}"
set -g status-left "#{?client_prefix,#[bg=#{@status_prefix_bg} fg=#{@status_prefix_fg} bold] ⌨  #S #[default],#[bold] #S #[default]}| "

# Simplify window names, bold current window
setw -g window-status-format " #I:#{window_name} "
setw -g window-status-current-format "#[bold] #I:#{window_name} #[default]"
setw -g window-status-separator ""

# status bar right side
set -g status-right ""

# Vim integration
set -g focus-events on

# Vim-like navigation in copy mode
setw -g mode-keys vi

#############
# SHORTCUTS #
#############

# Intuitive splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Swap window
bind-key S command-prompt -p "Swap with window: " "swap-window -t '%1' \; select-window -t '%1'"

#############
# OVERRIDES #
#############

# Import local overrides
if-shell '[ -f ~/.tmux.local.conf ]' "source-file ~/.tmux.local.conf"

